config/routes.rb
Rails.application.routes.draw do
  resources :linea_items

  devise_for :users
  resources :products
  resources :customers do
    resources :orders do
      resources :linea_items
    end
  end
  resources :orders do
    resources :products
  end
  resources :orders do
    resources :linea_items
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/linea_item.rb
class LineaItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/controllers/linea_items_controller.rb
class LineaItemsController < ApplicationController
  before_action :set_linea_item, only: [:show, :edit, :update, :destroy]
  before_action :set_order, only: [:create, :index]
  before_action :set_to_delete, only: [:destroy]

  # GET /linea_items
  # GET /linea_items.json
  def index
    if @order
      @linea_items = @order.linea_items.all
    end
  end

  # GET /linea_items/1
  # GET /linea_items/1.json
  def show
  end

  # GET /linea_items/new
  def new
    @linea_item = LineaItem.new
  end

  # GET /linea_items/1/edit
  def edit
  end
# customer_order_linea_items_path(:customer_id => @customer, :order_id => order)
# order_products_path(customer_id: params[:customer_id], order_id: params[:order_id])
  # POST /linea_items
  # POST /linea_items.json
  def create
    product = Product.find(params[:product_id])
    @linea_item = @order.add_product(product)

    respond_to do |format|
      if @linea_item.save
        format.html { redirect_to customers_url, notice: 'Linea item was successfully created.' }
        format.json { render :show, status: :created, location: @linea_item }
      else
        format.html { render :new }
        format.json { render json: @linea_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linea_items/1
  # PATCH/PUT /linea_items/1.json
  def update
    respond_to do |format|
      if @linea_item.update(linea_item_params)
        format.html { redirect_to @linea_item, notice: 'Linea item was successfully updated.' }
        format.json { render :show, status: :ok, location: @linea_item }
      else
        format.html { render :edit }
        format.json { render json: @linea_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linea_items/1
  # DELETE /linea_items/1.json
  # customer_order_linea_items_path(:customer_id => @customer, :order_id => order)
  def destroy
    @linea_item.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Item eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linea_item
      @linea_item = LineaItem.find(params[:id])
    end

    def set_order
      @order = Order.find(params[:order_id])
    end

    def set_to_delete
      @linea_item = LineaItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linea_item_params
      params.require(:linea_item).permit(:product_id, :order_id)
    end
end

app/helpers/linea_items_helper.rb
module LineaItemsHelper
end

app/views/linea_items/_form.html.erb
<%= form_with(model: linea_item, local: true) do |form| %>
  <% if linea_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linea_item.errors.count, "error") %> prohibited this linea_item from being saved:</h2>

      <ul>
      <% linea_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linea_items/edit.html.erb
<h1>Editing Linea Item</h1>

<%= render 'form', linea_item: @linea_item %>

<%= link_to 'Show', @linea_item %> |
<%= link_to 'Back', linea_items_path %>

app/views/linea_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de productos</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linea_items.each do |linea_item| %>
      <tr>
        <td><%= linea_item.product.description %></td>
        <td><%= linea_item.quantity %></td>
        <td><%= linea_item.total_price %></td>
        <td><%= link_to 'Eliminar', linea_item, method: :delete, data: { confirm: 'Seguro que quiere eliminar el producto' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar productos',  order_products_path(customer_id: params[:customer_id], order_id: params[:order_id]) %>
<!-- new_linea_item_path -->

app/views/linea_items/new.html.erb
<h1>New Linea Item</h1>

<%= render 'form', linea_item: @linea_item %>

<%= link_to 'Back', orders_path %>

app/views/linea_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @linea_item.product %>
</p>

<p>
  <strong>Order:</strong>
  <%= @linea_item.order %>
</p>

<%= link_to 'Edit', edit_linea_item_path(@linea_item) %> |
<%= link_to 'Back', linea_items_path %>