config/routes.rb
Rails.application.routes.draw do
  resources :linea_items

  devise_for :users
  resources :products
  resources :customers do
    resources :orders do
      resources :linea_items
    end
  end
  resources :orders do
    resources :products
  end
  resources :orders do
    resources :linea_items
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_many :linea_items
  validates :names, presence: true
  validates :surnames, presence: true
  validates :email, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, except: [:index, :new, :create]

  def index
    @customers = current_user.customers.all
  end
  #GET /customer/:id
    def show
      @customer = Customer.find(params[:id])
      @order = Order.new
    end
    #GET /customer/new
  def new
    @customer = Customer.new
  end
  #GET /customer/:id/edit
  def edit
    @customer = Customer.find(params[:id])
  end
  #POST /customer
  def create
    @customer = current_user.customers.new(customer_params)
    if @customer.save
      redirect_to action:"show", id:Customer.last.id
    else
      render :new
    end
  end
  #POST /customer
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end
  #POST /customer/:id
  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def validate_user
    redirect_to new_user_session_path, notice: "Necesitas iniciar sesión"
  end

  def customer_params
      params.require(:customer).permit(:names, :surnames, :email)
  end

end

app/views/customers/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> cliente</h1>
<%= form_for @customer do |f| %>
<% @customer.errors.full_messages.each do |message| %>
<div class="be-red white top-space">
  * <%= message %>
</div>
<%end%>
<div class="field">
  <%= f.text_field :names, placeholder: "Nombres", class:"form-control" %>
</div>
<div class="field">
  <%= f.text_field :surnames, placeholder: "Apellidos", class:"form-control"%>
</div>
<div class="field">
  <%= f.email_field :email, placeholder: "Email", class:"form-control"%>
</div>
<div class="field">
  <%= f.submit "Guardar", class:"btn be-red white"  %>
</div>
<%end%>

app/views/customers/edit.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form", name: "Editar" %>
  <%= link_to "Atrás", customer_path %>
</div>

app/views/customers/index.html.erb
<% @customers.each do |customer| %>
<h1><%= link_to customer.email, customer %></h1>
<div>
  Nombres: <%= customer.names %>,
  Apellidos: <%= customer.surnames %>
</div>
<% end %>
<br>
<%= link_to "Adicionar cliente", new_customer_path %>

app/views/customers/new.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form" %>
  <%= link_to 'Atrás', customers_path %>
</div>

app/views/customers/show.html.erb
<div class="row around-xs">
  <div class="col-xs-2">
    <div class="box"><h1>Nombres </h1> <%= @customer.names %></div>
  </div>
  <div class="col-xs-2">
    <div class="box"><h1>Apellidos </h1> <%= @customer.surnames %></div>
  </div>
  <div class="col-xs-2">
    <div class="box"><h1>Email</h1> <%= @customer.email %></div>
  </div>
</div>
<div class="field">
  <h3>Pedidos</h3>
  <table>
    <thead>
      <tr>
        <th>Subtotal |</th>
        <th>IVA: 16% |</th>
        <th>Total |</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @customer.orders.each do |order| %>
        <tr>
          <td><%= order.subtotal %></td>
          <td><%= order.iva %></td>
          <td><%= order.total %></td>
          <td><%= link_to "Ver", customer_order_linea_items_path(:customer_id => @customer, :order_id => order) %></td>
          <td><%= link_to 'Eliminar Orden', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <h3>Adicionar</h3>
  <%= render "orders/form" %>
</div>
<div class="row center-xs">
  <div class="col-xs-6">
        <div class="box">
            <%= link_to "Editar cliente", edit_customer_path(@customer) %>
            <%= link_to "Eliminar cliente", customer_url(@customer), method: :delete, class:"red" %>
        </div>
    </div>
</div>