config/routes.rb
Rails.application.routes.draw do
  resources :linea_items

  devise_for :users
  resources :products
  resources :customers do
    resources :orders do
      resources :linea_items
    end
  end
  resources :orders do
    resources :products
  end
  resources :orders do
    resources :linea_items
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :linea_items, dependent: :destroy

  def add_product(product)
    current_item = linea_items.find_by(product_id: product.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = linea_items.build(product_id: product.id)
    end
    current_item
  end

  def subtotal
    linea_items.to_a.sum { |item| item.total_price }
  end

  def iva
    subtotal * 16 / 100
  end

  def total
    subtotal + iva
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:create]
  # GET /orders
  # GET /orders.json
  def index
    if @customer
      @orders = @customer.orders.all
    else
      @customers = current_user.customers.all
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.customer = @customer
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order.customer, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@customer, @order]) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_orders.html.erb
<h3>Pedidos</h3>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% orders.each do |order| %>
      <tr>
        <%= order.linea_items %> - <h1><%= link_to "Ver", customer_order_linea_items_url %></h1>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', @order  %>

app/views/orders/index.html.erb
<% @customers.each do |customer| %>
<h3><%= link_to customer.names, customer%></h3>
<% customer.orders.each do |order| %>
<div>
  <%= link_to order.id, order%>
</div>
<% end %>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <!-- <%= @order.customer.names %> -->
  <% @order.linea_items do |linea_item| %>
  <h1>linea_item</h1>
  <% end %>
</div>

<!-- <%= link_to 'Edit', edit_order_path(@order) %> | -->
<%= link_to 'Back', orders_path %>