config/routes.rb
Rails.application.routes.draw do
  resources :linea_items

  devise_for :users
  resources :products
  resources :customers do
    resources :orders do
      resources :linea_items
    end
  end
  resources :orders do
    resources :products
  end
  resources :orders do
    resources :linea_items
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_linea_item
  has_many :linea_items
  belongs_to :user, optional: true
  validates :width, :height, presence: true
  validates :price, presence: true, length: { maximum: 7 }
  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :description, presence: true, length: { minimum: 8, too_short: "Descripción muy corta" }

# def not_referenced_by_any_linea_item
#   unless linea_items.empty?
#     errors.add(:base, "Hay pedidos con este producto")
#     throw :abort
# end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, except: [:index, :new, :create]

  def index
    @products = current_user.products.all.order("created_at desc")
  end
  #GET /product/:id
    def show
      @product = Product.find(params[:id])
    end
    #GET /product/new
  def new
    @product = Product.new
  end
  #GET /product/:id/edit
  def edit
    @product = Product.find(params[:id])
  end
  #POST /product
  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to action:"show", id:Product.last.id
    else
      render :new
    end
  end
  #POST /product
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  #POST /product/:id
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def validate_user
    redirect_to new_user_session_path, notice: "Necesitas iniciar sesión"
  end

  def product_params
      params.require(:product).permit(:width, :height, :price, :quantity, :description)
  end

end

app/views/products/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> producto</h1>
<%= form_for @product do |f| %>
<% @product.errors.full_messages.each do |message| %>
<div class="be-red white top-space">
  * <%= message %>
</div>
<%end%>
<div class="field">
  <%= f.text_field :width, placeholder: "ancho", class:"form-control" %>
</div>
<div class="field">
  <%= f.text_field :height, placeholder: "Alto", class:"form-control"%>
</div>
<div class="field">
  <%= f.number_field :price, placeholder: "Precio", class:"form-control"%>
</div>
<div class="field">
  <%= f.number_field :quantity, placeholder: "Cantidad", within:1...200, step:1, class:"form-control" %>
</div>
<div class="field">
  <%= f.text_area :description, placeholder: "Descripción", style:"height:150px;", class:"form-control" %>
</div>
<div class="field">
  <%= f.submit "Guardar", class:"btn be-red white"  %>
</div>
<%end%>

app/views/products/edit.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form", name: "Editar" %>
  <%= link_to 'Atrás', products_path %>
</div>

app/views/products/index.html.erb
<% @products.each do |product| %>
<h1><%= link_to product.description, product %></h1>
<div>
  Cantidad: <%= product.quantity %>,
  Precio: <%= product.price %>
  <% if request.env['PATH_INFO'] != "/products" %>
  - <%= button_to 'Adicionar a pedido', linea_items_url(order_id: params[:order_id], product_id: product) %>
  <%end%>
</div>
<% end %>
<br>
<div>
  <%= link_to "Adicionar nuevo producto", new_product_path %>
</div>

app/views/products/new.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form" %>
  <%= link_to 'Atrás', products_path %>
</div>

app/views/products/show.html.erb
<h1><%= @product.description %></h1>
<div class="row around-xs">
  <div class="col-xs-2">
    <div class="box"><h1>Cantidad</h1> <%= @product.quantity %></div>
  </div>
  <div class="col-xs-2">
    <div class="box"><h1>Ancho</h1> <%= @product.width %></div>
  </div>
  <div class="col-xs-2">
    <div class="box"><h1>Alto</h1> <%= @product.height %></div>
  </div>
  <div class="col-xs-2">
    <div class="box"><h1>Precio</h1> <%= @product.price %></div>
  </div>
</div>
<div class="row center-xs">
  <div class="col-xs-6">
        <div class="box">
            <%= link_to "Editar", edit_product_path(@product) %>
            <%= link_to "Eliminar", product_url(@product), method: :delete, class:"red" %>
        </div>
    </div>
</div>